---
sudo: true
language: python
python:
  - "3.8"
services:
  - docker
cache:
  - pip
install:
  - pip install --upgrade pip
script:
  - git clone git@github.com:ayyalaraju/docker-2ds.git ./
  - ../docker-2ds/bin/travis_build.sh
